<?php $user = new Handling();
      
	if($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['register'])){
		$userReg	= $user->userProfesionalRegistration($_POST);
	}
?>

<div class="row">
    <div class="col">
        <p class="h2 text-center p-3 text-primary mt-3">Seu Pefil Profissional</p>
    </div>
</div>

<?php if (isset($userReg)){ echo $userReg;} ?>

<div class="row">
    <div class="offset-3 col-6 justify-content-center mt-1">
        <form method="POST">
            <input type="text" class="form-control" name="cpf" placeholder="CPF" required>
            <input type="text" class="form-control" name="endereco" placeholder="Endereço">
            <input type="tel" class="form-control" name="contato" placeholder="Contato" maxlength="14">
            <select class="form-control" aria-placeholder="Especialidades" required>
                <option value="Spec">Especialidades</option>
                <option value="Spec">Tecnico de Enfermagem</option>
                <option value="Spec">Abastecedor de Caldei</option>
                <option value="Spec">Abastecedor de Combustível de Aeronave</option>
                <option value="Spec">Abatedor</option>
                <option value="Spec">Abelheiro</option>
                <option value="Spec">Abridor de Lã</option>
                <option value="Spec">Acabador de Calcados</option>
                <option value="Spec">Acabador de Embalagens (Flexíveis e Cartotecnicas)</option>
                <option value="Spec">Acabador de Pedras</option>
                <option value="Spec">Acafelador</option>
                <option value="Spec">Açaizeiro</option>
                <option value="Spec">Acepilhador de Metais</option>
                <option value="Spec">Acompanhante de Idosos</option>
                <option value="Spec">Açougueiro</option>
                <option value="Spec">Acrobata</option>
                <option value="Spec">Acupuntor</option>
                <option value="Spec">Acupunturista</option>
                <option value="Spec">Adestrador de Animais</option>
                <option value="Spec">Administrador</option>
                <option value="Spec">Administrador de Arquivos</option>
                <option value="Spec">Administrador de Banco de Dados</option>
                <option value="Spec">Administrador de Marketing</option>
                <option value="Spec">Administrador Financeiro</option>
                <option value="Spec">Administrador Público</option>
                <option value="Spec">Adubador</option>
                <option value="Spec">Advogado</option>
                <option value="Spec">Aeromoça</option>
                <option value="Spec">Afiador de Ferramentas</option>
                <option value="Spec">Afinador de Instrumentos Musicais</option>
                <option value="Spec">Agenciador de Cargas</option>
                <option value="Spec">Agenciador de Propaganda</option>
                <option value="Spec">Agenciador de Publicidade</option>
                <option value="Spec">Agente Administrativo</option>
                <option value="Spec">Agente Comunitário de Saúde</option>
                <option value="Spec">Agente de Carga</option>
                <option value="Spec">Agropecuarista</option>
                <option value="Spec">Ajudante de Açougueiro</option>
                <option value="Spec">Ajudante de Afiador</option>
                <option value="Spec">Ajudante de Banhos (vidros)</option>
                <option value="Spec">Ajudante de Carga e Descarga de Mercadoria</option>
                <option value="Spec">Ajudante de Cozinha</option>
                <option value="Spec">Ajudante de Eletricista</option>
                <option value="Spec">Alfaiate</option>
                <option value="Spec">Alimentador de Peixe</option>
                <option value="Spec">Alinhador de Pneus</option>
                <option value="Spec">Alinhador de Rodas</option>
                <option value="Spec">Alugador</option>
                <option value="Spec">Amaciador de Couros e Peles</option>
                <option value="Spec">Ambientador</option>
                <option value="Spec">Analista (psicanálise)</option>
                <option value="Spec">Analista Administrativo</option>
                <option value="Spec">Analista de Contabilidade</option>
                <option value="Spec">Analista de Estudos Econômicos</option>
                <option value="Spec">Analista de Marketing</option>
                <option value="Spec">Analista de Rede</option>
                <option value="Spec">Analista Econômico</option>
                <option value="Spec">Anestesiologista</option>
                <option value="Spec">Baba</option>
                <option value="Spec">Balconista</option>
                <option value="Spec">Banhista de Animais Domésticos</option>
                <option value="Spec">Barman</option>
                <option value="Spec">Bibliógrafo</option>
                <option value="Spec">Bibliotecário</option>
                <option value="Spec">Bilheteiro</option>
                <option value="Spec">Biógrafo</option>
                <option value="Spec">Biólogo</option>
                <option value="Spec">Biomédico</option>
                <option value="Spec">Boiadeiro</option>
                <option value="Spec">Bombeiro</option>
                <option value="Spec">Borracheiro</option>
                <option value="Spec">Botânico</option>
                <option value="Spec">Boxeador</option>
                <option value="Spec">Cabeleireiro</option>
                <option value="Spec">Caixa</option>
                <option value="Spec">Camareira</option>
                <option value="Spec">Camelô</option>
                <option value="Spec">Caminhoneiro</option>
                <option value="Spec">Carpinteiro</option>
                <option value="Spec">Carpinteiro Auxiliar</option>
                <option value="Spec">Carpinteiro Naval</option>
                <option value="Spec">Carregador</option>
                <option value="Spec">Carroceiro</option>
                <option value="Spec">Caranguejeiro</option>
                <option value="Spec">Carteiro</option>
                <option value="Spec">Cartógrafo</option>
                <option value="Spec">Castrador</option>
                <option value="Spec">Cavador </option>
                <option value="Spec">Caucheiro</option>
                <option value="Spec">Cenógrafo</option>
                <option value="Spec">Chacareiro</option>
                <option value="Spec">Chefe Administrativo</option>
                <option value="Spec">Chefe de Cozinha</option>
                <option value="Spec">Chefe de Escritório</option>
                <option value="Spec">Chefe de Orçamento</option>
                <option value="Spec">Chofer</option>
                <option value="Spec">Clarificador de Vinhos</option>
                <option value="Spec">Coletor de Lixo</option>
                <option value="Spec">Colunista</option>
                <option value="Spec">Comentarista</option>
                <option value="Spec">Comerciante</option>
                <option value="Spec">Compositor de Texto</option>
                <option value="Spec">Compositor de Imagens</option>
                <option value="Spec">Condutor de Máquinas</option>
                <option value="Spec">Condutor de Táxi</option>
                <option value="Spec">Confeiteiro</option>
                <option value="Spec">Consultor de Vendas</option>
                <option value="Spec">Consultor de Viagem</option>
                <option value="Spec">Consultor</option>
                <option value="Spec">Contador</option>
                <option value="Spec">Contabilista</option>
                <option value="Spec">Controlador de Vôo</option>
                <option value="Spec">Coordenador de Ensino</option>
                <option value="Spec">Coordenador Escolar</option>
                <option value="Spec">Coordenador Executivo</option>
                <option value="Spec">Cortador de Vidros</option>
                <option value="Spec">Costureiro</option>
                <option value="Spec">Coveiro</option>
                <option value="Spec">Cozinheiro</option>
                <option value="Spec">Criador de Abelhas</option>
                <option value="Spec">Criador de Animais</option>
                <option value="Spec">Criador de Gado</option>
                <option value="Spec">Criminalista</option>
                <option value="Spec">Critico</option>
                <option value="Spec">Cuidador de Idosos</option>
                <option value="Spec">Decorador</option>
                <option value="Spec">Defensor Publico</option>
                <option value="Spec">Defumador</option>
                <option value="Spec">Demolidor</option>
                <option value="Spec">Dentista</option>
                <option value="Spec">Desenhista</option>
                <option value="Spec">Desenvolvedor</option>
                <option value="Spec">Designer</option>
                <option value="Spec">Desinfestador</option>
                <option value="Spec">Destilador</option>
                <option value="Spec">Detetive de Polícia</option>
                <option value="Spec">Digitador</option>
                <option value="Spec">Distribuidor</option>
                <option value="Spec">Economista</option>
                <option value="Spec">Editor</option>
                <option value="Spec">Educador</option>
                <option value="Spec">Eletricista</option>
                <option value="Spec">Embalador</option>
                <option value="Spec">Empacotador</option>
                <option value="Spec">Empregada Doméstica</option>
                <option value="Spec">Encaixotador</option>
                <option value="Spec">Encanador</option>
                <option value="Spec">Enfermeiro</option>
                <option value="Spec">Engarrafador</option>
                <option value="Spec">Engenheiro</option>
                <option value="Spec">Escrivão</option>
                <option value="Spec">Speclhador</option>
                <option value="Spec">Farmacêutico</option>
                <option value="Spec">Faxineiro</option>
                <option value="Spec">Ferreiro</option>
                <option value="Spec">Fiscal</option>
                <option value="Spec">Forneiro</option>
                <option value="Spec">Fotografo</option>
                <option value="Spec">Frentista</option>
                <option value="Spec">Garçom</option>
                <option value="Spec">Gerente Administrativo e Financeiro</option>
                <option value="Spec">Gerente Comercial</option>
                <option value="Spec">Gerente</option>
                <option value="Spec">Gestor</option>
                <option value="Spec">Guarda de Segurança</option>
                <option value="Spec">Guarda Florestal</option>
                <option value="Spec">Guarda Ambiental</option>
                <option value="Spec">Guarda-civil</option>
                <option value="Spec">Guarda-costas</option>
                <option value="Spec">Inspetor</option>
                <option value="Spec">Instalador</option>
                <option value="Spec">Instrutor</option>
                <option value="Spec">Interprete</option>
                <option value="Spec">Jardineiro</option>
                <option value="Spec">Joalheiro</option>
                <option value="Spec">Jornalista</option>
                <option value="Spec">Legista</option>
                <option value="Spec">Lixeiro</option>
                <option value="Spec">Locutor</option>
                <option value="Spec">Manobrista</option>
                <option value="Spec">Maquiador</option>
                <option value="Spec">Maquinista </option>
                <option value="Spec">Marceneiro</option>
                <option value="Spec">Massagista</option>
                <option value="Spec">Mecânico</option>
                <option value="Spec">Médico</option>
                <option value="Spec">Mensageiro</option>
                <option value="Spec">Mergulhador</option>
                <option value="Spec">Montador</option>
                <option value="Spec">Motorista</option>
                <option value="Spec">Narrador</option>
                <option value="Spec">Operador de Caixa</option>
                <option value="Spec">Operador de Máquina</option>
                <option value="Spec">Padeiro</option>
                <option value="Spec">Pedreiro</option>
                <option value="Spec">Perito Criminal</option>
                <option value="Spec">Pescador</option>
                <option value="Spec">Pintor</option>
                <option value="Spec">Policial</option>
                <option value="Spec">Porteiro</option>
                <option value="Spec">Professor de Ensino Fundamental de Primeira a Quarta Séries</option>
                <option value="Spec">Professor de Ensino Fundamental Nas Quatro Primeiras Séries</option>
                <option value="Spec">Professor de Ensino Profissionalizante no Ensino de Nível Médio</option>
                <option value="Spec">Professor de Ensino Superior</option>
                <option value="Spec">Programador</option>
                <option value="Spec">Radiologista</option>
                <option value="Spec">Recepcionista</option>
                <option value="Spec">Recreador</option>
                <option value="Spec">Relações Publicas</option>
                <option value="Spec">Revisor</option>
                <option value="Spec">Revisor Gráfico</option>
                <option value="Spec">Sambista</option>
                <option value="Spec">Secretário(A)</option>
                <option value="Spec">Segurança Comunitário</option>
                <option value="Spec">Segurança de Evento</option>
                <option value="Spec">Segurança Pessoal</option>
                <option value="Spec">Serrador</option>
                <option value="Spec">Servente de Pedreiro</option>
                <option value="Spec">Sorveteiro</option>
                <option value="Spec">Superintendente Administrativo e Financeiro</option>
                <option value="Spec">Supervisor Administrativo</option>
                <option value="Spec">Supervisor</option>
                <option value="Spec">Técnico Ambiental</option>
                <option value="Spec">Técnico Agrícola</option>
                <option value="Spec">Técnico Analista</option>
                <option value="Spec">Técnico de Análise Química</option>
                <option value="Spec">Técnico de Áudio (rádio)</option>
                <option value="Spec">Técnico de Artes Gráficas</option>
                <option value="Spec">Técnico de Contabilidade</option>
                <option value="Spec">Técnico de Enfermagem</option>
                <option value="Spec">Técnico de Equipamentos Elétricos</option>
                <option value="Spec">Técnico de Indústria Eletrônica</option>
                <option value="Spec">Técnico de Laboratório</option>
                <option value="Spec">Técnico de Manutenção</option>
            </select>
            <select class="form-control" aria-placeholder="Especialidades">
                <option value="Spec">Escolha sua 2º Especialidade</option>
                <option value="Spec">Tecnico de Enfermagem</option>
                <option value="Spec">Abastecedor de Caldei</option>
                <option value="Spec">Abastecedor de Combustível de Aeronave</option>
                <option value="Spec">Abatedor</option>
                <option value="Spec">Abelheiro</option>
                <option value="Spec">Abridor de Lã</option>
                <option value="Spec">Acabador de Calcados</option>
                <option value="Spec">Acabador de Embalagens (Flexíveis e Cartotecnicas)</option>
                <option value="Spec">Acabador de Pedras</option>
                <option value="Spec">Acafelador</option>
                <option value="Spec">Açaizeiro</option>
                <option value="Spec">Acepilhador de Metais</option>
                <option value="Spec">Acompanhante de Idosos</option>
                <option value="Spec">Açougueiro</option>
                <option value="Spec">Acrobata</option>
                <option value="Spec">Acupuntor</option>
                <option value="Spec">Acupunturista</option>
                <option value="Spec">Adestrador de Animais</option>
                <option value="Spec">Administrador</option>
                <option value="Spec">Administrador de Arquivos</option>
                <option value="Spec">Administrador de Banco de Dados</option>
                <option value="Spec">Administrador de Marketing</option>
                <option value="Spec">Administrador Financeiro</option>
                <option value="Spec">Administrador Público</option>
                <option value="Spec">Adubador</option>
                <option value="Spec">Advogado</option>
                <option value="Spec">Aeromoça</option>
                <option value="Spec">Afiador de Ferramentas</option>
                <option value="Spec">Afinador de Instrumentos Musicais</option>
                <option value="Spec">Agenciador de Cargas</option>
                <option value="Spec">Agenciador de Propaganda</option>
                <option value="Spec">Agenciador de Publicidade</option>
                <option value="Spec">Agente Administrativo</option>
                <option value="Spec">Agente Comunitário de Saúde</option>
                <option value="Spec">Agente de Carga</option>
                <option value="Spec">Agropecuarista</option>
                <option value="Spec">Ajudante de Açougueiro</option>
                <option value="Spec">Ajudante de Afiador</option>
                <option value="Spec">Ajudante de Banhos (vidros)</option>
                <option value="Spec">Ajudante de Carga e Descarga de Mercadoria</option>
                <option value="Spec">Ajudante de Cozinha</option>
                <option value="Spec">Ajudante de Eletricista</option>
                <option value="Spec">Alfaiate</option>
                <option value="Spec">Alimentador de Peixe</option>
                <option value="Spec">Alinhador de Pneus</option>
                <option value="Spec">Alinhador de Rodas</option>
                <option value="Spec">Alugador</option>
                <option value="Spec">Amaciador de Couros e Peles</option>
                <option value="Spec">Ambientador</option>
                <option value="Spec">Analista (psicanálise)</option>
                <option value="Spec">Analista Administrativo</option>
                <option value="Spec">Analista de Contabilidade</option>
                <option value="Spec">Analista de Estudos Econômicos</option>
                <option value="Spec">Analista de Marketing</option>
                <option value="Spec">Analista de Rede</option>
                <option value="Spec">Analista Econômico</option>
                <option value="Spec">Anestesiologista</option>
                <option value="Spec">Baba</option>
                <option value="Spec">Balconista</option>
                <option value="Spec">Banhista de Animais Domésticos</option>
                <option value="Spec">Barman</option>
                <option value="Spec">Bibliógrafo</option>
                <option value="Spec">Bibliotecário</option>
                <option value="Spec">Bilheteiro</option>
                <option value="Spec">Biógrafo</option>
                <option value="Spec">Biólogo</option>
                <option value="Spec">Biomédico</option>
                <option value="Spec">Boiadeiro</option>
                <option value="Spec">Bombeiro</option>
                <option value="Spec">Borracheiro</option>
                <option value="Spec">Botânico</option>
                <option value="Spec">Boxeador</option>
                <option value="Spec">Cabeleireiro</option>
                <option value="Spec">Caixa</option>
                <option value="Spec">Camareira</option>
                <option value="Spec">Camelô</option>
                <option value="Spec">Caminhoneiro</option>
                <option value="Spec">Carpinteiro</option>
                <option value="Spec">Carpinteiro Auxiliar</option>
                <option value="Spec">Carpinteiro Naval</option>
                <option value="Spec">Carregador</option>
                <option value="Spec">Carroceiro</option>
                <option value="Spec">Caranguejeiro</option>
                <option value="Spec">Carteiro</option>
                <option value="Spec">Cartógrafo</option>
                <option value="Spec">Castrador</option>
                <option value="Spec">Cavador </option>
                <option value="Spec">Caucheiro</option>
                <option value="Spec">Cenógrafo</option>
                <option value="Spec">Chacareiro</option>
                <option value="Spec">Chefe Administrativo</option>
                <option value="Spec">Chefe de Cozinha</option>
                <option value="Spec">Chefe de Escritório</option>
                <option value="Spec">Chefe de Orçamento</option>
                <option value="Spec">Chofer</option>
                <option value="Spec">Clarificador de Vinhos</option>
                <option value="Spec">Coletor de Lixo</option>
                <option value="Spec">Colunista</option>
                <option value="Spec">Comentarista</option>
                <option value="Spec">Comerciante</option>
                <option value="Spec">Compositor de Texto</option>
                <option value="Spec">Compositor de Imagens</option>
                <option value="Spec">Condutor de Máquinas</option>
                <option value="Spec">Condutor de Táxi</option>
                <option value="Spec">Confeiteiro</option>
                <option value="Spec">Consultor de Vendas</option>
                <option value="Spec">Consultor de Viagem</option>
                <option value="Spec">Consultor</option>
                <option value="Spec">Contador</option>
                <option value="Spec">Contabilista</option>
                <option value="Spec">Controlador de Vôo</option>
                <option value="Spec">Coordenador de Ensino</option>
                <option value="Spec">Coordenador Escolar</option>
                <option value="Spec">Coordenador Executivo</option>
                <option value="Spec">Cortador de Vidros</option>
                <option value="Spec">Costureiro</option>
                <option value="Spec">Coveiro</option>
                <option value="Spec">Cozinheiro</option>
                <option value="Spec">Criador de Abelhas</option>
                <option value="Spec">Criador de Animais</option>
                <option value="Spec">Criador de Gado</option>
                <option value="Spec">Criminalista</option>
                <option value="Spec">Critico</option>
                <option value="Spec">Cuidador de Idosos</option>
                <option value="Spec">Decorador</option>
                <option value="Spec">Defensor Publico</option>
                <option value="Spec">Defumador</option>
                <option value="Spec">Demolidor</option>
                <option value="Spec">Dentista</option>
                <option value="Spec">Desenhista</option>
                <option value="Spec">Desenvolvedor</option>
                <option value="Spec">Designer</option>
                <option value="Spec">Desinfestador</option>
                <option value="Spec">Destilador</option>
                <option value="Spec">Detetive de Polícia</option>
                <option value="Spec">Digitador</option>
                <option value="Spec">Distribuidor</option>
                <option value="Spec">Economista</option>
                <option value="Spec">Editor</option>
                <option value="Spec">Educador</option>
                <option value="Spec">Eletricista</option>
                <option value="Spec">Embalador</option>
                <option value="Spec">Empacotador</option>
                <option value="Spec">Empregada Doméstica</option>
                <option value="Spec">Encaixotador</option>
                <option value="Spec">Encanador</option>
                <option value="Spec">Enfermeiro</option>
                <option value="Spec">Engarrafador</option>
                <option value="Spec">Engenheiro</option>
                <option value="Spec">Escrivão</option>
                <option value="Spec">Speclhador</option>
                <option value="Spec">Farmacêutico</option>
                <option value="Spec">Faxineiro</option>
                <option value="Spec">Ferreiro</option>
                <option value="Spec">Fiscal</option>
                <option value="Spec">Forneiro</option>
                <option value="Spec">Fotografo</option>
                <option value="Spec">Frentista</option>
                <option value="Spec">Garçom</option>
                <option value="Spec">Gerente Administrativo e Financeiro</option>
                <option value="Spec">Gerente Comercial</option>
                <option value="Spec">Gerente</option>
                <option value="Spec">Gestor</option>
                <option value="Spec">Guarda de Segurança</option>
                <option value="Spec">Guarda Florestal</option>
                <option value="Spec">Guarda Ambiental</option>
                <option value="Spec">Guarda-civil</option>
                <option value="Spec">Guarda-costas</option>
                <option value="Spec">Inspetor</option>
                <option value="Spec">Instalador</option>
                <option value="Spec">Instrutor</option>
                <option value="Spec">Interprete</option>
                <option value="Spec">Jardineiro</option>
                <option value="Spec">Joalheiro</option>
                <option value="Spec">Jornalista</option>
                <option value="Spec">Legista</option>
                <option value="Spec">Lixeiro</option>
                <option value="Spec">Locutor</option>
                <option value="Spec">Manobrista</option>
                <option value="Spec">Maquiador</option>
                <option value="Spec">Maquinista </option>
                <option value="Spec">Marceneiro</option>
                <option value="Spec">Massagista</option>
                <option value="Spec">Mecânico</option>
                <option value="Spec">Médico</option>
                <option value="Spec">Mensageiro</option>
                <option value="Spec">Mergulhador</option>
                <option value="Spec">Montador</option>
                <option value="Spec">Motorista</option>
                <option value="Spec">Narrador</option>
                <option value="Spec">Operador de Caixa</option>
                <option value="Spec">Operador de Máquina</option>
                <option value="Spec">Padeiro</option>
                <option value="Spec">Pedreiro</option>
                <option value="Spec">Perito Criminal</option>
                <option value="Spec">Pescador</option>
                <option value="Spec">Pintor</option>
                <option value="Spec">Policial</option>
                <option value="Spec">Porteiro</option>
                <option value="Spec">Professor de Ensino Fundamental de Primeira a Quarta Séries</option>
                <option value="Spec">Professor de Ensino Fundamental Nas Quatro Primeiras Séries</option>
                <option value="Spec">Professor de Ensino Profissionalizante no Ensino de Nível Médio</option>
                <option value="Spec">Professor de Ensino Superior</option>
                <option value="Spec">Programador</option>
                <option value="Spec">Radiologista</option>
                <option value="Spec">Recepcionista</option>
                <option value="Spec">Recreador</option>
                <option value="Spec">Relações Publicas</option>
                <option value="Spec">Revisor</option>
                <option value="Spec">Revisor Gráfico</option>
                <option value="Spec">Sambista</option>
                <option value="Spec">Secretário(A)</option>
                <option value="Spec">Segurança Comunitário</option>
                <option value="Spec">Segurança de Evento</option>
                <option value="Spec">Segurança Pessoal</option>
                <option value="Spec">Serrador</option>
                <option value="Spec">Servente de Pedreiro</option>
                <option value="Spec">Sorveteiro</option>
                <option value="Spec">Superintendente Administrativo e Financeiro</option>
                <option value="Spec">Supervisor Administrativo</option>
                <option value="Spec">Supervisor</option>
                <option value="Spec">Técnico Ambiental</option>
                <option value="Spec">Técnico Agrícola</option>
                <option value="Spec">Técnico Analista</option>
                <option value="Spec">Técnico de Análise Química</option>
                <option value="Spec">Técnico de Áudio (rádio)</option>
                <option value="Spec">Técnico de Artes Gráficas</option>
                <option value="Spec">Técnico de Contabilidade</option>
                <option value="Spec">Técnico de Enfermagem</option>
                <option value="Spec">Técnico de Equipamentos Elétricos</option>
                <option value="Spec">Técnico de Indústria Eletrônica</option>
                <option value="Spec">Técnico de Laboratório</option>
                <option value="Spec">Técnico de Manutenção</option>
            </select>
            <input type="text" class="form-control" name="experiencias" placeholder="Experiencias">
            <input type="text" class="form-control" name="work_bio" placeholder="Fale sobre você" maxlength="255">
            <button name="text" class="btn btn-outline-primary btn-lg mt-2">
                Salvar
            </button>
        </form>
        <form action="" method="post" enctype="multipart/form-data">
            <span>Envie seu currículo</span>
            <input type="file" name="curriculo" id="">
        </form>
    </div>
</div>